🔀 :: (#9) [date] 여러 날짜 타입간의 차이 구하는 메소드 추가
team-xquare/java-utils pull request #11
Opened 2021-06-10 17:27 UTC by jhhong0509

LocalDateTime - LocalDateTime
LocalDate - LocalDateTime
LocalDateTime - LocalDate
LocalDate - LocalDate
Date - Date
LocalDateTime - Date
Date - LocalDateTime
Date - LocalDate
LocalDate - Date
LocalDateTime - Calendar
Calendar - LocalDateTime
LocalDate - Calendar
Calendar	- LocalDate
Date - Calendar
Calendar	- Date
Calendar	- Calendar
간의 연산 메소드

2021-06-10 23:28 UTC, smoothbear requested changes
감사합니다 🔥 DateCompare에 대해서 말씀드린 부분만 확인해주세요!

2021-06-10 23:28 UTC, smoothbear commented on lib/src/main/java/io/xquare/date/DateCompare.java
> +        System.out.println(date);
혹시 여기서 System.out.println()을 호출하는 이유가 있을까요?

2021-06-10 23:28 UTC, smoothbear commented on lib/src/main/java/io/xquare/date/DateCompare.java
> +                .atZone(ZoneId.systemDefault())
ZoneId.of("+09:00"); 와 같은 설정으로 Time Zone 설정을 JVM에 위임하기 보다는 한국 표준시(+0900)로 설정하여 일관성 있게 유지하는 것은 어떤가요?

2021-06-11 00:30 UTC, jhhong0509 commented on lib/src/main/java/io/xquare/date/DateCompare.java
> +        System.out.println(date);
오 없애는거 까먹었다

2021-06-11 00:33 UTC, jhhong0509 commented on lib/src/main/java/io/xquare/date/DateCompare.java
> +                .atZone(ZoneId.systemDefault())
근데 system의 서버 시간을 따라가야지 자신의 애플리케이션을 따라가지 않을까요?

2021-06-11 07:49 UTC, smoothbear approved these changes
감사합니다 😮

2021-06-11 07:49 UTC, merged